settings:
  title: 'Tiny Status Page'
  url: 'https://status.tinyforest.rocks' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Only Kinda Broke'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'We Fucked'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: plex-tinyforest-rocks
    name: The Tiny Plex
    description: 'All good in the hood' # default=empty
    url: 'https://plex.tinyforest.rocks/web/index.html#!/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: request-tinyforest-rocks
    name: The Request System
    description: 'All good in the hood.' # default=empty
    url: 'https://request.tinyforest.rocks/login'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: access-tinyforest-rocks
    name: The Access System
    description: 'All good in the hood' # default=empty
    url: 'https://access.tinyforest.rocks/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

